#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    filetree_direction="left"
    default_indent=4
    #autocomplete_method = "asyncomplete"
    autocomplete_method = "coc"
    #enable_ycm = 1
    enable_smooth_scrolling = 0
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"

# Enable autocomplete layer

[[layers]]
name = 'core'
enable_smooth_scrolling = 0

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name="lang#go"

[[layers]]
name="lang#python"

[[layers]]
name="lang#c"
clang_executable = "/usr/bin/clang"

#enable_clang_syntax_highlight = true
[layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "format"

[[layers]]
  name = "gtags"
#gtagslabel = "pygments"

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
  "go"
  "python"
#  "css"
#  "javascript"
#  "javascriptreact"
]

[[layers]]
name = "checkers"
[[layers]]
name = "git"
[[layers]]
name = "lang#vim"
[[layers]]
name = "lang#json"
[[layers]]
name = "lang#sh"
[[layers]]
name = "lang#javascript"
[[layers]]
name = "lang#html"
