#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer, the value of this option is a string.
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors, the type of the value is boolean, true or false.
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    # Display file type icon on the tabline, If you do not have nerd fonts
    # installed, please change the value to false
    enable_tabline_filetype_icon = true
    # Display current mode text on statusline, by default It is disabled,
    # only color will be changed when switch modes.
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true

    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    windows_smartclose = 'qq'

    # custom
    filetree_direction="left"
    default_indent=4
    # coc
    autocomplete_method = "coc"
    # bootstrap
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"

[[layers]]
name = 'core'
enable_smooth_scrolling = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name="lang#go"

[[layers]]
name="lang#python"

[[layers]]
name="lang#c"
clang_executable = "/usr/bin/clang"

#enable_clang_syntax_highlight = true
[layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "format"

[[layers]]
  name = "gtags"
#gtagslabel = "pygments"

[[layers]]
name = "lsp"
filetypes = [
  "c",
  "cpp"
  "go"
  "python"
#  "css"
#  "javascript"
#  "javascriptreact"
]

[[layers]]
name = "checkers"
[[layers]]
name = "git"
[[layers]]
name = "lang#vim"
[[layers]]
name = "lang#json"
[[layers]]
name = "lang#sh"
[[layers]]
name = "lang#javascript"
[[layers]]
name = "lang#html"
